### ISSUE TITLE
Initial login prompt to use Amazon account

### ISSUE THREAD

**Issue by kenmaina** [schmittx/home-assistant-eero#10]
Please add amazon account login for some international users.

**Comment by schmittx** [comment]
I'll be glad to, but I don't use Amazon login method myself so I need some help from someone who does. If you're familiar with logging HTTP requests to understand the Amazon login process, then we can definitely work on it.

**Comment by schmittx** [comment]
Closing in favor of #17 (adding Amazon login support)
