### ISSUE TITLE
Request for Optional Network and Device Connection for Sensors

### ISSUE THREAD

**Issue by Jvella94** [schmittx/home-assistant-eero#101]
Apologies if it's intended behaviour but could I kindly ask if its possible for a small Quality of Life change for default device names? All the "Entities" of Devices have the same structure of: {Network Name} {Device Name with Connection Type}

Would it be possible to add as an option to not have the network name for them? I only have the one network, so all the wording is redundant for the device names, Changing each one would take me a while as I can't easily substring them. There would also be the issue of having to repeat it for each new device added.

On the dashboards, users would have to keep reading past the Network name to find what sensor they're looking at.

Another small change might be, apart from a couple of exceptions (The device tracke and"Connected" sensor), to remove the Connection type from the Device names as well. That would reduce the wording even less but that isn't as verbose of an issue as the network one since those are suffixes.

Image below of the issue, with "Mainframe" being my Network name.

![image](https://github.com/user-attachments/assets/c580c1dc-38c1-44ed-9189-ce37fdb88635)

**Comment by schmittx** [comment]
An option to disable the network name prefix has been released in [1.6.3](https://github.com/schmittx/home-assistant-eero/releases/tag/1.6.3).

However, I don't plan on removing the connection type suffix (or adding an option to). I fear it may create confusion and it would require a fair amount of extra code for a relatively specific usage case. I may reconsider this in the future, but for now it's low on the priority list.

**Comment by Jvella94** [comment]
Cheers for the quick fix and makes sense for the suffix :) Works like a charm!
