### ISSUE TITLE
Parsing response was unsuccessful with status code: 500

### ISSUE THREAD

**Issue by ralphbk** [schmittx/home-assistant-eero#105]
The eero integration is failing to start up with the following error: 

> This error originated from a custom integration.
> 
> Logger: custom_components.eero.api
> Source: custom_components/eero/api/__init__.py:174
> integration: eero (documentation, issues)
> First occurred: 09:34:35 (5 occurrences)
> Last logged: 09:43:17
> 
> Parsing response was unsuccessful with status code: 500

It may be related to the latest Home Assistant 2024.11.2 update. (Or eeroOS v7.6.3-103?)

What can I do here?

**Comment by pietrouk** [comment]
I'm experiencing the same issue

**Comment by ralphbk** [comment]
I see the Devices tab in the eero app is showing "There was an error with your request, please try again later." The problem _might_ be [on the eero server side](https://community.eero.com/t/k9jmp6/no-devices-showing-connected-but-60-of-them-are#m1ha20j).

**Comment by duffyd** [comment]
> I see the Devices tab in the eero app is showing "There was an error with your request, please try again later." The problem _might_ be [on the eero server side](https://community.eero.com/t/k9jmp6/no-devices-showing-connected-but-60-of-them-are#m1ha20j).

Actually, you may be right because in the Eero app it just says "Connecting" at the top and this status message never changes.

**Comment by schmittx** [comment]
Yeah, the eero servers appear to be the problem ([link](https://www.reddit.com/r/amazoneero/comments/1gu0evx/eeros_working_but_shows_its_trying_to_connect_to/)). Nothing that this integration can do.

**Comment by ralphbk** [comment]
Correct. The eero app is now showing devices again, and after an HA restart, the eero integration is working again. Panic over. (Although it might be nice to have more elegant way of handling this in the integration, no?)
