### ISSUE TITLE
"Not a valid add-on repository

### ISSUE THREAD

**Issue by goochmd** [schmittx/home-assistant-eero#107]
Hi! I am new to HAOS, and I have tried to download by typing in the exact repository link, and it shows the error in the image below (If it cannot be seen, it says "https://github.com/schmittx/home-assistant-eero/ is not a valid add-on repository"
![image](https://github.com/user-attachments/assets/4c998314-9309-4c1e-a861-ced09b403785)

**Comment by schmittx** [comment]
This is a custom component and repository. You can manually place the files in the `custom_components` folder, or Use HACS. Follow the instructions for installing HACS first ([link](https://www.hacs.xyz/docs/use/)), and then add this repo as a custom repo within HACS ([link](https://www.hacs.xyz/docs/faq/custom_repositories/)).
