### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Davecl** [schmittx/home-assistant-eero#11]
Hi
I have installed as a custom repo in HACS but when I go to integrations to add it, it doesn't show up in the integrations list to install

**Comment by schmittx** [comment]
Try resetting your browser cache or doing a hard refresh. Instructions for that vary by browser so just do a quick search if you're not familiar.

**Comment by Davecl** [comment]
Thanks.. After 2 or 3 goes, the hard refresh did it 👍

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
