### ISSUE TITLE
How to display all connected devices in a card?

### ISSUE THREAD

**Issue by philhzss** [schmittx/home-assistant-eero#13]
Hi!! Firstly thank you for this, really neat! I've only been using Home Assistant for a few days so sorry if this is basic and I'm missing something, but how could I make a card (like a dashboard/lovelace card) that can display all connected devices ?

I ticked all the devices that are currently connected during setup, but I'd like to have a card in my overview that automatically updates every time a known (or new) device connects to my Eero, and lists all the currently connected devices. Is this possible?

Thank you!!!

**Comment by schmittx** [comment]
Please check the HA documentation and/or forums for more help. Your question is regarding a HA feature and not specific to this repo, so this issue will be closed.
