### ISSUE TITLE
No function anymore since 2021.6.1

### ISSUE THREAD

**Issue by lukaaars** [schmittx/home-assistant-eero#14]
The custom integration 'eero' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by schmittx** [comment]
Try updating to the latest version (1.1.3) or this and re-confirm. The manifest version tag was added.

**Comment by lukaaars** [comment]
Thanks, that worked :)
