### ISSUE TITLE
Bandwith Monitoring

### ISSUE THREAD

**Issue by pnichols77** [schmittx/home-assistant-eero#16]
Apologies if this isn't the right way to ask this - but is there a possibility the integration will ever be able to show bandwith being used, either per device or for the whole network?

**Comment by schmittx** [comment]
The integration support data usage metrics (upload and download) on a network, profile, and individual device level. However, it's currently configured to only allow those metrics for network with an active eero Secure subscription (I personally have a subscription and am only able to test that way). If these metrics are available without a subscription, please feel free to submit a PR.
