### ISSUE TITLE
integration not possibile with 2020.12.7

### ISSUE THREAD

**Issue by pilot1981** [schmittx/home-assistant-eero#2]
Hi,
I installed custom repository via HACS, but when I go in integration UI->add it's not possible to find eero integration...

**Comment by schmittx** [comment]
I'm assuming you're referring to 2020.12.1? I don't think x.7 is available?

Regardless, have you tried hard-refreshing the browser page (to clear the cache) before searching?

**Comment by pilot1981** [comment]
I have HASSIO where 2020.12.7 is vastest stable version

**Comment by schmittx** [comment]
I don't believe so, [GitHub](https://github.com/home-assistant/core/releases) shows 2020.12.1 as latest.

Did hard-refreshing work though?

**Comment by pilot1981** [comment]
solved clearing browser caching.

thanks.
