### ISSUE TITLE
Feature request: Enable Home Assistant's use of eero 6's zigbee hardware

### ISSUE THREAD

**Issue by DavidPhillipOster** [schmittx/home-assistant-eero#20]
Home Assistant's should be able to use eero 6's zigbee hardware by sending the eero 6 commands over local wifi, so it works even when there is no internet, and one should be able to install zigbee devices locally, even when there is no internet and no Amazon account. Does this repository already enable this?

**Comment by schmittx** [comment]
No, this repo does not support that. I personally do not have any eero 6 hardware so I don't plan to pursue it either. However, feel free to develop on your own and submit a PR, or fork for yourself.
