### ISSUE TITLE
HACS installation (project still alive?)

### ISSUE THREAD

**Issue by trailsurfer604** [schmittx/home-assistant-eero#22]
I've been trying to install this integration via HACS, but no luck - it does not find this repository or integration.

Is the issue that the project hasn't been published to the latest version of HACS or something else?

**Comment by RosemaryOrchard** [comment]
Did you add this as a custom repository?

**Comment by schmittx** [comment]
You need to add to HACS as a custom repo, as @RosemaryOrchard mentioned, and as stated in the readme.
