### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by plasterer41** [schmittx/home-assistant-eero#33]
Would it be possible to identify which devices are connected to (or leaves) a specific eero within a house with multiple eeros - would give the opportunity to use the eero as room presence detection devices.

**Comment by schmittx** [comment]
> Would it be possible to identify which devices are connected to (or leaves) a specific eero within a house with multiple eeros - would give the opportunity to use the eero as room presence detection devices.

There's already a sensor created for each Eero device which shows the total number of clients connected to that device. Additionally, a device tracker entity is created for each client (if enabled during initial setup or via configure) which contains an attribute showing which Eero device that specific client is connected to. Between these two entities, I think you should already have what you need. Let me know if I misunderstood your request though.

**Comment by schmittx** [comment]
Closing for now, feel free to comment or re-open if needed.
