### ISSUE TITLE
Feature Request: Tracking Activity per Device

### ISSUE THREAD

**Issue by dmccabe79** [schmittx/home-assistant-eero#38]
It would be EXTREMELY useful if we could track, within HA, U/D activity rate for selected devices. That would be extremely useful for tracking who's awake.

**Comment by schmittx** [comment]
> It would be EXTREMELY useful if we could track, within HA, U/D activity rate for selected devices. That would be extremely useful for tracking who's awake.

If all you're looking for is something to determine if a client is awake/active or not, what about a "last active" sensor returning a timestamp? Something like `"last_active": "2023-05-11T11:32:58.876Z",`. Returning U/D rate via polling every so often seems strange, especially if you're only looking to see if a client is active or not.

**Comment by schmittx** [comment]
Added additional sensors in 1.2.2
