### ISSUE TITLE
Releases should be tagged as x.y.z (without v prefix)

### ISSUE THREAD

**Issue by rsnodgrass** [schmittx/home-assistant-eero#4]
I noticed that HACS treats released tagged with a "v" prefix to the version as a string and does not compare the x.y.z values to determine which is the latest.  For the next release it might be best to switch to the x.y.z numeric format.

**Comment by schmittx** [comment]
Thanks for the advice, I don't personally use HACS so I probably wouldn't have caught this. I just pushed a new release and have updated the versioning format accordingly.
