### ISSUE TITLE
Feature Reguest

### ISSUE THREAD

**Issue by ffpllc** [schmittx/home-assistant-eero#44]
Hi,

I had this installed for a few months but it wouldn't load correctly. When I did the update to 2023.2.4 it started working for me, yippee!

One feature request I'd like to suggest. Would it be possible to add a sensor similar to connected_clients, that indicates the number of "Other" connected clients?

I have all my normal devices categorized in Eero (Home, Entertainment, etc) but I'd like to know the number of uncategorized devices that on the network.

I use Eeros in a vacation rental and I'd like to know when guests are at the house and when they have left.

Thanks!

**Comment by schmittx** [comment]
Added as attributes to the `Connected Clients` sensor entity in [1.2](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.0). Let me know if this is sufficient.

**Comment by ffpllc** [comment]
That's exactly what I was looking for! Thanks so much
