### ISSUE TITLE
After updating to 1.1.0, sensors show Unavailable

### ISSUE THREAD

**Issue by waltlillyman** [schmittx/home-assistant-eero#5]
After updating to 1.1.0 via Community, Pending updates, then restarting Home Assistant Core (running in Docker on Ubuntu 18.04), my Eero sensors show Unavailable.
This log file entry appears at HA startup:
```
2021-01-29 06:58:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry My_Name for eero
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eero/__init__.py", line 135, in async_setup_entry
    conf_activity = options.get(CONF_ACTIVITY, data[CONF_ACTIVITY])
KeyError: 'activity'
```
When I revert to 1.0.3, sensors appear again.

**Comment by schmittx** [comment]
Sorry about that, I'll have to push a quick fix for that this weekend.

Another option in the meantime is to delete and re-setup the integration within Home Assistant.

**Comment by waltlillyman** [comment]
No worries, thanks for your efforts!

**Comment by schmittx** [comment]
@waltlillyman I just pushed an update that should fix the problem. Let me know if you still encounter problems.

**Comment by DrGomek** [comment]
Update did not work for me, but delete/reinstall worked fine.

**Comment by schmittx** [comment]
What errors did you get after updating to 1.1.1?

**Comment by DrGomek** [comment]
Sorry, I didn't save the logs.  I had the same problem as @waltlillyman : all of the entities showed as offline.  When I would try to investigate the integration in the UI, it would spin off with a message like "Please wait while installing" but then never got anywhere.

It seemed like it was "crashing" (for lack of a better word) on startup.

I'm new here, so if there is some log I can grab for you I'm willing to.

**Comment by waltlillyman** [comment]
My upgrade from 1.0.3 to 1.1.1 worked perfectly, thanks, @schmittx !

**Comment by schmittx** [comment]
Good, glad to hear it. I'll close the issue now but please re-open or a submit a new one if you still have problems.
