### ISSUE TITLE
2023.5 update

### ISSUE THREAD

**Issue by michaelthompson1991** [schmittx/home-assistant-eero#50]
Since I upgraded HA to 2023.5 i get the following error https://imgur.com/a/0k5KWs5 Ive checked the logs and it says https://imgur.com/a/o756KXT and followed  by Error handling request 11:06:18 – (ERROR) eero (custom integration)

Ive tried disabling bad re-enabling and deleted and reinstalled the integration and have the same problem.

Let me know if you need anymore info and ill try and help, with my limited abilities!

**Comment by blizzrdof77** [comment]
This is fixed by PR #47

**Comment by blizzrdof77** [comment]
Duplicate of #48

**Comment by michaelthompson1991** [comment]
Do I need to update anything to fix it?

**Comment by blizzrdof77** [comment]
For now, you can just update the file manually in custom_components

**Comment by michaelthompson1991** [comment]
I'm afraid I'm not sure how to do that 🤣
