### ISSUE TITLE
unable to select networks

### ISSUE THREAD

**Issue by hunleyd** [schmittx/home-assistant-eero#52]
Just installed 1.2.0 today after discovering this integration. i'm on 2023.5.1 of HA. Integration installs fine, asks me for my email/phone and then the code, and then takes me to the 'select networks' screen and doesn't show me either network that i manage.
![20230505131658](https://user-images.githubusercontent.com/2753418/236524604-57b86237-a37a-4507-b310-871994e17532.png)

**Comment by thayerfox** [comment]
Same for me.

**Comment by schmittx** [comment]
Weird, just confirmed it works fine for me, at least as a clean install.

**Comment by bbilek** [comment]
Same here - cannot select networks - updated from the previous version

**Comment by JRascagneres** [comment]
Same here. I removed and re-oadded the integration to test it. Still same issue

**Comment by sonikro** [comment]
Same for me, on HA 2023.4.6. I downgraded to 1.1.4 and everything went back to normal. Apparently, it's some bug in version 1.2.0

**Comment by JRascagneres** [comment]
> Same for me, on HA 2023.4.6. I downgraded to 1.1.4 and everything went back to normal. Apparently, it's some bug in version 1.2.0

That doesn't work in 2023.5 though unfortunately

**Comment by pietrouk** [comment]
Same here. I removed and re-added the integration to test it. Still same issue - cannot select any networks too.

**Comment by blizzrdof77** [comment]
It works for me!

**Comment by massari46** [comment]
Same here. I removed and re-added the integration to test it. Still same issue - cannot select any networks too.

**Comment by gawelko** [comment]
Same issue

**Comment by schmittx** [comment]
Glad to hear it works for at least someone else. Can someone with the problem post their logs?

**Comment by JRascagneres** [comment]
> Glad to hear it works for at least someone else. Can someone with the problem post their logs?

I can do anything you may need to debug it. Nothing in the logs about `eero` though. Just shows empty networks. Happy to provide anything that might help if you tell me how / what:
![image](https://user-images.githubusercontent.com/3264971/236654042-8eef417d-ce7f-49e4-9f7e-01f0a06c8acc.png)

**Comment by schmittx** [comment]
Click Sumbit and let the integration initialize without any network selected. Then click Configure to access the options (ensure advanced mode is enabled for your HA profile) and enable the Save Responses option. You should see a folder appear under the API folder within Eero. There should be a json file with "networks" in the name, among other ones.

**Comment by JRascagneres** [comment]
@schmittx Any way I can provide this to you a bit better? Looks like there are IP addresses and things that I'd rather not post here publically.

**Comment by schmittx** [comment]
Yeah, understood. I don't think I actually need the file details, just wanted to confirm the API calls were working and you were getting a non-empty response.

I assume that there were no networks to select even after clicking Configure after letting it initialize?

**Comment by JRascagneres** [comment]
Yeah no networks to configure. I have sent you the json on discord if you're interested. I also have an accounts response in that directory.

**Comment by pietrouk** [comment]
@schmittx After enabling the "Save responses" option, I can see the _2_2_networks_5493493.json file in the api/responses folder. All the network details are there and updated, but I still see no network to select and no devices or entities imported.

**Comment by capjay1** [comment]
Ditto. With "Save responses" option, I get the networks json file with the correct network name and all relevant info. Yet the network name is blank in the dialog.

**Comment by superpower10** [comment]
I am in Bridge-Mode, no eero plus and same here. No network. Everything blank

**Comment by JRascagneres** [comment]
I have provided some info to @schmittx on discord. Hopefully enough to help. My theory is it works if you're paying for premium based on my limited interpretation of logs. @blizzrdof77 Are you paying for premium given it works for you?

**Comment by blizzrdof77** [comment]
@JRascagneres - yes, I am subscribed to eero plus.

**Comment by blizzrdof77** [comment]
Also, not in bridge mode.

**Comment by JRascagneres** [comment]
Right okay I'm going to assume thats the issue then... Just errors out early if you're not subscribed... @schmittx

**Comment by schmittx** [comment]
Thanks to @JRascagneres for the help in tracking down the problem, I'll have an update out shortly with a fix.

**Comment by schmittx** [comment]
Just published an update that should fix this, let me know how it works.

**Comment by JRascagneres** [comment]
> Just published [1.2.1](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.1) that should fix this, let me know how it works.

Looks good to me! 😄 Thanks for the fix

**Comment by sonikro** [comment]
> Just published [1.2.1](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.1) that should fix this, let me know how it works.

Just upgraded and now everything is working. Thanks for the great work

**Comment by pietrouk** [comment]
Same here, all working now, thank you @schmittx!

**Comment by bbilek** [comment]
Thank you for you dedication!! Looks great and it seems all is back to a healthy state ☺️

**Comment by hunleyd** [comment]
Indeed, 1.2.1 works here. Thank you!

**Comment by karlaq** [comment]
Eero is in bridge mode with two devices connected to a UnFi switch.

Can't get network to show up even though I can see the '_2_2_networks..json' file.
100% sure I am signing in using a normal e-mail. Also tried sign in using mobile phone number.

I am on latest versions of eero plugin and HA. Running HA using VM in bridge network mode.

Below is the last line from debug:
2023-07-06 10:55:06.387 DEBUG (MainThread) [custom_components.eero] Finished fetching Eero (ACCOUNT NAME) data in 2.834 seconds (success: True)
