### ISSUE TITLE
Shows firmware update on HA Settings page for devices which are old and no longer receiving firmware updates

### ISSUE THREAD

**Issue by jeffalperin** [schmittx/home-assistant-eero#53]
Running version 1.2.1 of the Eero integration.  
I have two old Eero devices running eeroOS v6.12.2-68.  The Eero app reports that "Firmware updates are no longer supported."  And "Warning  This eero device stopped receiving software updates on Sep 30, 2022."

The Home Assistant Settings page shows updates available for the devices (eeroOS v6.14.0-4275)
![image](https://github.com/schmittx/home-assistant-eero/assets/42316774/dfeeee52-9b75-4e5b-9fa3-7fcc84e5d8ab)

![image](https://github.com/schmittx/home-assistant-eero/assets/42316774/9886c5f1-f063-4f63-977d-e6051e83fa6b)

 but the devices cannot be updated.

Can the Eero integration be modified so that firmware updates are not shown for devices which can no longer be updated?  Alternatively, can the notification be cleared so it doesn't continue to appear on the Settings page.  (Clicking the Install button causes a brief appearance of a progress bar, 1 or 2 seconds, but nothing else happens.)

**Comment by schmittx** [comment]
Sure, I can look into this. Go to the integration page in Home Assistant and click configure, then enable "Save Responses" (ensure your HA profile is set to "Advanced" first). Share the "networks" or "update data" json and I'll see if something in there signifies if a device can't receive further updates. Feel free to email or find me on Discord rather than posting the files publicly.

**Comment by jeffalperin** [comment]
Thank you!  Json files attached.

--ja

**Comment by jeffalperin** [comment]
Hi, Matt.  Just checking to be sure that the json files I sent last night were what you needed.

--ja

**Comment by schmittx** [comment]
> Hi, Matt. Just checking to be sure that the json files I sent last night were what you needed.

I saw your post but there weren't any JSON files attached. Are you able to DM me on Discord @schmittx?

**Comment by jeffalperin** [comment]
I’m a Discord newbie, but I believe I just uploaded the files to you.  I’m @jalperin.

--ja

From: Jeff Alperin
Sent: Wednesday, May 10, 2023 1:21 PM
To: schmittx/home-assistant-eero ***@***.***>; schmittx/home-assistant-eero ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [schmittx/home-assistant-eero] Shows firmware update on HA Settings page for devices which are old and no longer receiving firmware updates (Issue #53)

Hi, Matt.  Just checking to be sure that the json files I sent last night were what you needed.

--ja

**Comment by schmittx** [comment]
Fixed in 1.2.2
