### ISSUE TITLE
Eero wont update

### ISSUE THREAD

**Issue by michaelthompson1991** [schmittx/home-assistant-eero#56]
Hi, I’ve noticed HA said there was an update when I think it normally comes through HACS. Now it wont seem to update, see video https://imgur.com/a/1ntLGuj

**Comment by blizzrdof77** [comment]
@michaelthompson1991  -- Those are firmware update notifications for your actual Eero devices. 🙃  Hope that helps!

**Comment by michaelthompson1991** [comment]
Yeah I noticed that in the end, I didn’t know eero integrated so well with HA!Sent from my iPhoneOn 7 Jun 2023, at 03:05, Ben Wagner ***@***.***> wrote:﻿
@michaelthompson1991  -- Those are firmware update notifications for your actual Eero devices. 🙃  Hope that helps!
