### ISSUE TITLE
Logging in with email does not load any networks

### ISSUE THREAD

**Issue by nzneil22** [schmittx/home-assistant-eero#57]
When i try to setup the integration in HAOS on rpi4, after login i do not get any networks available to add to my instance. I confirm that i see the network when i login hsing the same method on the eero app.

**Comment by schmittx** [comment]
Any chance you're using the sign-in-with-Amazon method for the app? If so, this integration doesn't support it.

Otherwise, can you turn on response saving via Options and share your (redacted) logs and responses? You can email or find me on Discord (same username as GitHub) if you'd rather not post publicly.

**Comment by nzneil22** [comment]
Hi Matt, thanks for your reply. Im 100% sure that i am logging in using a non-amazon account. 

The first error in the log is:
This error originated from a custom integration.

Logger: custom_components.eero.config_flow
Source: custom_components/eero/config_flow.py:72
Integration: eero (documentation, issues)
First occurred: 23:39:54 (1 occurrences)
Last logged: 23:39:54

Status: 401, Error Message: error.login.unknown

Then this is followed by:
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/eero/config_flow.py:75
Integration: eero (documentation, issues)
First occurred: 23:39:54 (1 occurrences)
Last logged: 23:39:54

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/config_flow.py", line 75, in async_step_user
    self.user_input[CONF_USER_TOKEN] = self.response["user_token"]
                                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by schmittx** [comment]
Thanks for the detail.

The error message `Status: 401, Error Message: error.login.unknown` is showing the login you entered is unknown.

Are you using the same credentials (either email or phone number) to login as the app? If using a phone number, make sure you're entering the country code first.

**Comment by nzneil22** [comment]
Yes i am sure that i am entering the correct credentials

**Comment by schmittx** [comment]
@nzneil22 Are you still having this problem? Any updates?

**Comment by nzneil22** [comment]
Hi, i will try again later today. Just noticed there is a new version
1.3.1, i will update and retry.

Thanks

**Comment by nzneil22** [comment]
Seems that i am now getting this error:

This error originated from a custom integration.

Logger: custom_components.eero
Source: helpers/update_coordinator.py:262
Integration: eero (documentation, issues)
First occurred: June 30, 2023 at 13:50:28 (1 occurrences)
Last logged: June 30, 2023 at 13:50:28

Timeout fetching Eero (Neil Borg) data

**Comment by schmittx** [comment]
Are you still getting the same `Status: 401, Error Message: error.login.unknown` error as before?

**Comment by nzneil22** [comment]
No the error now is: 
![Screenshot_20230704_084917_Home Assistant](https://github.com/schmittx/home-assistant-eero/assets/88832123/a48ef4a8-2565-499d-8e97-9d8070f250e1)

**Comment by schmittx** [comment]
OK, it clearly seems to be something with your login and verification methods. This integration only support the basic sign-in via Eero credentials, and it seems to be working for well for others, so there's gotta be something unique about your situation. That being said, some things to try or confirm:

1) Re-confirm you don't use seem weird sign-in method for Eero (Amazon, ISP credentials, etc.).
2) Re-confirm you're including a country code if using a mobile phone number to sign-in.
3) If you're truly stuck, try creating another Eero account to use for this integration. Then add that account as an admin for your existing network.

**Comment by nzneil22** [comment]
Hi i have tried all of the steps you mentioned, but it still does not show any network. I will try downgrading the version of the component maybe that helps. This used to work before

Thanks

**Comment by nzneil22** [comment]
Downgrading to version 1.3.0 did not fix the issue. I have no errors in the log

**Comment by schmittx** [comment]
I just released [1.4.1](https://github.com/schmittx/home-assistant-eero/releases/tag/1.4.1) which adds more `debug` level logging to help diagnose this. Please update and try a fresh install of the integration, then share your results.

**Comment by nzneil22** [comment]
I now get this error:
This error originated from a custom integration.

Logger: custom_components.eero.api
Source: custom_components/eero/api/__init__.py:187
Integration: eero (documentation, issues)
First occurred: 22:31:30 (2 occurrences)
Last logged: 22:31:45

Exception raised, status code: 403, text: {'meta': {'code': 403, 'server_time': '2023-07-10T20:31:30.162Z', 'error': 'error.network.premium.not.capable'}}
Exception raised, status code: 403, text: {'meta': {'code': 403, 'server_time': '2023-07-10T20:31:45.607Z', 'error': 'error.network.premium.not.capable'}}

Also i am getting this screen now after the login.
![Screenshot_20230710_223140_Home Assistant](https://github.com/schmittx/home-assistant-eero/assets/88832123/70b3ed5e-b5cc-41c7-a8a8-51d25bd16a2d)

**Comment by schmittx** [comment]
> Exception raised, status code: 403, text: {'meta': {'code': 403, 'server_time': '2023-07-10T20:31:30.162Z', 'error': 'error.network.premium.not.capable'}}
> Exception raised, status code: 403, text: {'meta': {'code': 403, 'server_time': '2023-07-10T20:31:45.607Z', 'error': 'error.network.premium.not.capable'}}

This is progress at least, it's clearly letting you login and verify. This concern looks like a problem with verifying Eero Plus status.

Are you able to enable response logging and share the `_2_2_networks_xxxxxxx.json` file with me? I recommend you add me on Discord (same username, @schmittx) so we can chat directly and avoid posting your responses publicly.

The screenshot you shared is the advanced options screen. Previously only available if you selected `Configure` within Home Assistant after setting up the integration. For 1.4.1, I added it to the end of the flow for initial setup as well. Looks like to need to hard refresh your browser so the frontend refreshes and shows the text.

**Comment by chapinb** [comment]
I am getting the same error, `error.network.premium.not.capable`, on version 1.4.2. Where can i find the response logging to help with troubleshooting?

**Comment by artphdent** [comment]
I am getting the same problem, no networks show when I am configuring the integration. I do not log on with amazon credentials

**Comment by nzneil22** [comment]
Same here, the issue still persists

**Comment by daviegeepers** [comment]
I also cannot log in at all with email and I don't get the code when I enter in my phone number (US: 16175551212).

**Comment by ronbarr** [comment]
I’m getting the same issue and logs as nzneil did on Jun 12. It’s a fresh install. I’m using email. 

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 9:11:51 PM (2 occurrences)
Last logged: 9:14:36 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eero/config_flow.py", line 77, in async_step_user
    self.user_input[CONF_USER_TOKEN] = self.response["user_token"]
                                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by ronbarr** [comment]
Never mind - I forgot I had converted to an Amazon account.

**Comment by yarafie** [comment]
Hi @schmittx Im getting same problem as nzneil22. Was there a resolution i can try?

**Comment by yarafie** [comment]
Has anyone resolved this?

**Comment by schmittx** [comment]
I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

**Comment by nzneil22** [comment]
Hi schmittx, the beta worked for me :) thanks

**Comment by chrissimsuk1** [comment]
beta worked for me thanks

**Comment by schmittx** [comment]
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0).
