### ISSUE TITLE
Getting IP addresses of connected clients

### ISSUE THREAD

**Issue by ErickJR13** [schmittx/home-assistant-eero#58]
Hi! 

Would it be possible for the integration to pull the internal IP addresses of connected clients? I have some home servers that change their IP addresses over a reboot, and it'd be cool to grab the new IP from a custom dashboard, for example. 

(Huge thanks for this integration, by the way!)

**Comment by schmittx** [comment]
Yeah, internal IP address is easy enough. In fact, it's already an attribute on the `device_tracker` entity for any enabled client.

![image](https://github.com/schmittx/home-assistant-eero/assets/630673/f06cf8f2-6420-4a64-8ae4-783e95d67e64)

Does that achieve what you're looking for?

I suppose a new standalone `sensor` entity could be added with the IP address, but you can also do that currently with a template sensor of your own pulling from the `device_tracker` entity. So, I think that seems a little needless.

Just a side comment, if you're worried about IP addresses changing over a reboot, why not just create IP reservations within the Eero app?

**Comment by ErickJR13** [comment]
Oh, I didn't know it was an attribute of the device_tracker entity. Thank you for pointing this out! 

The only oddity I noticed, and it is likely that this is on me given I am using [a custom lovelace](https://github.com/benct/lovelace-multiple-entity-row), is that the entity card says that the device in question is "Home" but I would know when it is Away or Home. 

Here is a screenshot of what I mean: 

![Screenshot 2023-06-30 at 9 45 00 AM](https://github.com/schmittx/home-assistant-eero/assets/18079184/0226391c-48eb-4f24-9b0f-c56b2b578a61)

This works for now! If doing an standalone sensor with the IP address is ever in the pipeline, I'd appreciate it! It will simplify things for me haha

> Just a side comment, if you're worried about IP addresses changing over a reboot, why not just create IP reservations within the Eero app?

I am having an issue with Proxmox changing the IP addresses of the containers/VMs I set up. Eero sees these device as private, so it isn't able to directly target the devices for IP reservation. While I work on a solution, I added the IP address of the containers to my dashboard so I can easily find/see them. 

On another note, is there a way I can donate to the project? This has been a great addition to my smart home setup!

**Comment by schmittx** [comment]
I just pushed a new release with a standalone sensor added for client IP address, check out [1.3.2](https://github.com/schmittx/home-assistant-eero/releases/tag/1.3.2).

Regarding the `home` (connected to network) vs. `away` (not connected to network) state, those are the standard states for the `device_tracker` entity.

**Comment by ErickJR13** [comment]
You are amazing, thank you so much!! My dashboard look neater and I was able to setup some notification automations in a iffy! 


Please let me know if you have a tip jar or something along the lines. Happy to donate for your amazing work!

**Comment by schmittx** [comment]
Great, glad you're happy!

I appreciate the willingness to donate, but I don't have anything setup and no plans to do so. I'll let you know if that changes.
