### ISSUE TITLE
Switch guest network QR code to image entity for the 2023-7 release

### ISSUE THREAD

**Issue by JRascagneres** [schmittx/home-assistant-eero#60]
Home Assistant 2023-7 are getting image entities. One of the examples stated is even for use in QR codes for wifi connections. Current change log:

https://rc.home-assistant.io/blog/2023/06/28/release-20237/#image-entities

**Comment by schmittx** [comment]
Awesome, I wasn't aware of this, thanks for the heads up. I'll definitely plan to implement it once 2023.7 is released.

**Comment by schmittx** [comment]
I just released [1.4.0](https://github.com/schmittx/home-assistant-eero/releases/tag/1.4.0) with support for `image` entities, try it out and let me know if there's any feedback.

**Comment by JRascagneres** [comment]
Seems to work well but can we have it so the image shows the default image like previous when the network isn't enabled?

**Comment by JRascagneres** [comment]
I'll give it a try! I think your proposal there makes sense... Having the image modified to just say something like "QR code unavailable when network disabled" or something similar, other than that I don't have a great idea.

**Comment by JRascagneres** [comment]
Sorry not done this yet... Am I being dumb... I have an empty tickbox 
![image](https://github.com/schmittx/home-assistant-eero/assets/3264971/20d2ae83-6282-40f3-98e6-c80137ae2201)

**Comment by schmittx** [comment]
You need to hard refresh your browser for the text to show up.

**Comment by JRascagneres** [comment]
Yeah I tried that, can't get it to show up for some reason. Same on mobile... Can activate it anyway, assume that will work?

**Comment by JRascagneres** [comment]
Yeah I activated that checkbox and it worked. Would recommend a note on the image like you suggested such as "must enable network to show QR code"
