### ISSUE TITLE
Weekly data usage showing lifetime usage

### ISSUE THREAD

**Issue by Brooklyn-Sid** [schmittx/home-assistant-eero#64]
When I use the sensor.[network name]_data_usage_week shows an astronomical value that I think is the lifetime usage of my router versus that week. Is there a setting I need to change either in the integration or on my router to get it to show up correctly?

For what it's worth, Home Assistant shows the same value for this sensor regardless if it's day, week or month.

Sid

**Comment by TheRealFalseReality** [comment]
Do you need eero plus to get that sensor? I don't see it in HA and not on the subscription. Thanks!

**Comment by schmittx** [comment]
@Brooklyn-Sid Are you still experiencing this concern? Default units for data_usage are in `kb` so it'll be a big number by default. But you can change the units within Home Assistant UI.

**Comment by schmittx** [comment]
I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

**Comment by schmittx** [comment]
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0).
