### ISSUE TITLE
in log Exception raised, 

### ISSUE THREAD

**Issue by responde** [schmittx/home-assistant-eero#66]
Apparently it works correctly, but this error comes out from time to time

"Este error se originó a partir de una integración personalizada.

Logger: custom_components.eero.api
Source: custom_components/eero/api/__init__.py:206
Integration: eero (documentation, issues)
First occurred: 04:07:15 (5 occurrences)
Last logged: 12:52:48

Exception raised, status code: 500, text: {'error': {'id': '82gfapnei'}}
Exception raised, status code: 500, text: {'error': {'id': '82ggdjmjp'}}
Exception raised, status code: 500, text: {'error': {'id': '82gh4pgn5'}}
Exception raised, status code: 500, text: {'error': {'id': '82ghch683'}}
Exception raised, status code: 500, text: {'error': {'id': '82gi200c7'}}"

**Comment by schmittx** [comment]
Seems like an error outside the scope of this integration. Are you still experiencing the problem?

**Comment by schmittx** [comment]
I just pushed a new [update](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0) that may fix this. Please update and confirm. If you still have issues, feel free to re-open.
