### ISSUE TITLE
Blank Config Page when Setting Up

### ISSUE THREAD

**Issue by Jvella94** [schmittx/home-assistant-eero#69]
On setting up the current version I received a blank config page after setting up the eero Secure entities, not sure what the options are or why it occurred. Can help if needed but need setup instructions on how to turn on logging (didn't say anything in homeassitant.log file)

- Home Assistant 2023.10.0
- HACS 1.33.0
- Eero 1.4.3

![image](https://github.com/schmittx/home-assistant-eero/assets/20588370/5808bdc3-3e8c-4a1c-b31f-21c69840aded)

**Comment by schmittx** [comment]
This integration only support English translation, any chance you've set Home Assistant to a different language? Also, try clearing your cache and refreshing.

**Comment by schmittx** [comment]
I just pushed a new [update](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0) that may fix this. Please update and confirm. If you still have issues, feel free to re-open.
