### ISSUE TITLE
Not able to discover second network

### ISSUE THREAD

**Issue by MnemoBRMC** [schmittx/home-assistant-eero#71]
Hi
I have two eero networks in two different houses. In both case the wifi name is the same, to be able to autoconnect my devices when I move from a house to the other.
The point is that I installed the eero integration in the first house's home assistant instance and everything went well. Then I installed my eero network in the second house and tried to install the eero integration in it's own home assistant instance, but it only retrieved the network in the first house.

So I am not sure what the limitation is, if is just not able to retrieve two networks, or if its related to the fact that both networks have the same name.

**Comment by schmittx** [comment]
Any chance both networks are located in the same city and region (ex. "Los Angeles, California")?

**Comment by schmittx** [comment]
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0). Be sure to use the network nickname feature in Eero app to help identify your networks. This integration will pull that nickname.
