### ISSUE TITLE
Howto find root cause paused WIFI device

### ISSUE THREAD

**Issue by pilot1981** [schmittx/home-assistant-eero#72]
Hi,
In last month I have a wifi device (echo dot v3) pushed in eero app.

if I remove pause from eero app, it pause again itself after a couple of hours…

I disabled HA Integration and it don’t pause it again.

I don’t created any automation using eero integration.

how I can understand which is root cause?

regards

**Comment by schmittx** [comment]
Are you still experiencing this problem? I just re-confirmed that pausing/resuming an individual device (client) works fine for me.

**Comment by pilot1981** [comment]
> Are you still experiencing this problem? I just re-confirmed that pausing/resuming an individual device (client) works fine for me.

I found an automatin of HA is stopping WIFI of my device using HA integration

**Comment by schmittx** [comment]
Understood, closing this issue then.
