### ISSUE TITLE
Devices names on network?

### ISSUE THREAD

**Issue by kedarv** [schmittx/home-assistant-eero#74]
I saw https://github.com/343max/eero-client implements a method to fetch devices connected to the network -- and I see that the numeric value of devices connected is exposed. is there any way to get the actual names into HA to be used as entities? for example, could then build automations like `when device XYZ connects to network...`

**Comment by schmittx** [comment]
You can enable/disable specific devices (aka "clients") through the configurations options UI. Multiple entities will be created for each configured device (client), one of which is a binary sensor that is `on` when the device is connected to the network.

**Comment by kedarv** [comment]
nice, that did the trick, thanks!
