### ISSUE TITLE
Current version shows no networks after verifying by email

### ISSUE THREAD

**Issue by RuneMason1** [schmittx/home-assistant-eero#75]
![image_2024-01-01_223650927](https://github.com/schmittx/home-assistant-eero/assets/78815068/d9c881c2-3d4d-4c98-a2ae-32dbae1e6ae6)

**Comment by rolandflores** [comment]
Having the same issue here.

**Comment by yarafie** [comment]
Same here it happened after subscribing to eero plus for me

**Comment by dennyreiter** [comment]
Same here I just noticed.  My network was there but none of the sensors were available.  I deleted it and tried to re-add, but no networks were available.

**Comment by PacoCT** [comment]
The same issue here.
My config:
- HA on virtuaalbox (Host: Windows 11)
- USB WiFi Dongle passed to VirtualBox through USB Filter
- Second (non-Amazon) account as an admin of eero app/network, even though I am logged in the app using the amazon account

A dumb question: In order eero custom integration to work, HA has to have access to eero network using WiFi, or it can manage the eero network though a hard-wired connection?

**Comment by schmittx** [comment]
@PacoCT Home Assistant doesn't need direct access to the configured network (Wi-Fi or ethernet). The integration works by communicating with eero's API only. Eero's API handles the communication between the actual network(s).

Besides @PacoCT is everyone else using a **non-Amazon** account to login to this integration?

**Comment by yarafie** [comment]
@schmittx 
I'm using a non-amazon account (Set up another admin account), but as I mentioned It was working before I subscribed to eero plus (Google Play Subscription)
For another reason I cancelled by eero plus subscription and it started working again.

**Comment by schmittx** [comment]
@yarafie Understood. From this issue and others it seems that eero API returns multiple values to indicate if a subscription is present/valid, it's hard to capture and test them all.

**Comment by RuneMason1** [comment]
Secondary admin invited. No eero plus sub. Eero is ISP provided, if that changes anything.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PacoCT** [comment]
@schmittx 
I'm now logged in to the eero app as the second administrator (non-amazon account).
I do have a Eero Plus subscription (original/first administrator).
I am not able to see any network in the pop-up
![image](https://github.com/schmittx/home-assistant-eero/assets/12235299/5676a6a1-dc1c-43b2-bc10-6048f88b221d)

**Comment by schmittx** [comment]
@RuneMason1 I don't have any experience with ISP-provided eero devices. I'd assume they're no different but can't be sure...

@PacoCT You should be able to proceed through the setup even though no networks are available. Then, ensure you have advanced mode enabled for your profile in Home Assistant. After that, go back to the Eero integration and click "Configure" and proceed through the flow again but this time you'll get an additional screen with debugging options. Enable the option to save responses and then find `_2_2_account.json` after clicking "Finish" (and letting Home Assistant re-initialize the integration"). Share the contents of that file here please, being sure to redact any personal information.

**Comment by dennyreiter** [comment]
Here is the json account file from my integration

On the setup flow, there is a second checkbox, under save server responses, but no description of what it should be?

I hope this helps, and thanks!

[dennyreiter_2_2_account_redacted.json](https://github.com/schmittx/home-assistant-eero/files/14464206/dennyreiter_2_2_account_redacted.json)

**Comment by dennyreiter** [comment]
Also, here is the log file:
[eero20240301.log](https://github.com/schmittx/home-assistant-eero/files/14464238/eero20240301.log)

**Comment by schmittx** [comment]
@dennyreiter Thanks, this helps a lot. Can you check one more thing for me please? Look for `_2_2_networks_8796037.json`, within that file should be a key and dict pair like the following:

```
        "premium": {
            "capable": true,
            "requirements": {
                "has_allowed_country_code": true,
                "has_allowed_group": true,
                "has_min_mobile_version": true,
                "has_min_version": true,
                "has_proper_connection_mode": true,
                "has_proper_org_configs": true,
                "has_proper_owned_network_count": true,
                "has_proper_owner_role": true
            }
        },
```

Can copy and paste here? I want to confirm my theory.

**Comment by dennyreiter** [comment]
```        "premium": {
            "capable": false,
            "requirements": {
                "has_allowed_country_code": true,
                "has_allowed_group": true,
                "has_min_mobile_version": true,
                "has_min_version": true,
                "has_proper_connection_mode": false,
                "has_proper_org_configs": true,
                "has_proper_owned_network_count": true,
                "has_proper_owner_role": true
            }
        },
```

**Comment by schmittx** [comment]
@dennyreiter Perfect, thanks. The `"capable": false` bit is causing the problem I believe. Not sure what necessarily makes this `true` or `false` but the `false` is triggering the error in your logs. I'll push a beta version shortly for you to try.

**Comment by dennyreiter** [comment]
Awesome.  Yes it's very confusing.  In some places it says Premiu is yes, then others Capable, false.

**Comment by PacoCT** [comment]
> @PacoCT You should be able to proceed through the setup even though no networks are available. Then, ensure you have advanced mode enabled for your profile in Home Assistant. After that, go back to the Eero integration and click "Configure" and proceed through the flow again but this time you'll get an additional screen with debugging options. Enable the option to save responses and then find `_2_2_account.json` after clicking "Finish" (and letting Home Assistant re-initialize the integration"). Share the contents of that file here please, being sure to redact any personal information.

@schmittx 
I see @dennyreiter already provided the data you needed. In any case, here it goes the info I've got
[_2_2_account_edited.json](https://github.com/schmittx/home-assistant-eero/files/14468153/_2_2_account_edited.json)

        "premium": {
            "capable": false,
            "requirements": {
                "has_allowed_country_code": true,
                "has_allowed_group": true,
                "has_min_mobile_version": true,
                "has_min_version": true,
                "has_proper_connection_mode": false,
                "has_proper_org_configs": true,
                "has_proper_owned_network_count": true,
                "has_proper_owner_role": true
            }
        },

Regards,

**Comment by schmittx** [comment]
@dennyreiter @PacoCT I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

**Comment by PacoCT** [comment]
> @dennyreiter @PacoCT I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

@schmittx thank you very much to try solving this issue. I really appreciate your work

I'd be glad to help you troubleshoot the eero integration issue in Home Assistant. 

**Steps I've followed**:
1. Downloaded Beta Version and installed the beta version.  Replaced the eero folder in the config/custom_components folder.
2. Removed Standard eero integration using Home Assistant.
3. Install eero again using Home Assitant
4. Logged In the eero app with Non-Amazon Account

**Observed Issues**:

1. No Network Detection in the eero configure option.
2. Missing text in Pop-up Windows: The pop-up windows that normally appear in Home Assistant are not displaying any text.
![Screenshot 2024-03-05 143147](https://github.com/schmittx/home-assistant-eero/assets/12235299/c9b52149-76f4-48c6-b8a9-100b963bb66e)
![Screenshot 2024-03-05 143223](https://github.com/schmittx/home-assistant-eero/assets/12235299/b287cda7-cbbd-494a-8757-23645d57eadb)


4. In the Error Logs there are two errors in the logs, 
![Screenshot 2024-03-05 152338](https://github.com/schmittx/home-assistant-eero/assets/12235299/82395bb2-56ed-4ecc-8309-8aa5bc08fb2e)

_log_Error1_1431h_20240305.txt_, and 

![Screenshot 2024-03-05 152413](https://github.com/schmittx/home-assistant-eero/assets/12235299/c1ee9363-83fa-416d-8a63-99b5a77de893)

_log_Error2_1431h_20240305.txt_

5. The files (edited) in the eero\api\responses are attached as well

I hope my report helps you in going deeper in the issues.

[log_Error2_1431h_20240305.txt](https://github.com/schmittx/home-assistant-eero/files/14496991/log_Error2_1431h_20240305.txt)
[_2_2_account_edited.json](https://github.com/schmittx/home-assistant-eero/files/14496992/_2_2_account_edited.json)
[_2_2_networks_7038562_Edited.json](https://github.com/schmittx/home-assistant-eero/files/14496993/_2_2_networks_7038562_Edited.json)
[log_Error1_1431h_20240305.txt](https://github.com/schmittx/home-assistant-eero/files/14496994/log_Error1_1431h_20240305.txt)

Paco

**Comment by RuneMason1** [comment]
I haven't done logs or anything yet. But paco has exactly my issue. If you need information from another user, please let me know

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dennyreiter** [comment]
The beta solved my issue and everything seems to be back.  Thank you!

**Comment by schmittx** [comment]
@PacoCT I'm not entirely sure what's causing your errors. I think it's because you're trying to run two versions of the same integration in parallel (it looks like you renamed some things to `eero_standard`)? The errors regarding `error.network.premium.not.capable` have been addressed in the beta, and I can tell from the formatting of the exception logs that they're coming from the (older) non-beta version. Please re-try with the [latest](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b1) beta.

@RuneMason1 The first beta had a minor error regarding getting release notes, I just pushed an [update](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b1) for the beta. Try it out and let me know if it resolves your issues.

**Comment by RuneMason1** [comment]
It appears that the beta has a fix! It worked! Everything detected. The only gripe is that the dialogs in the wired/wireless clients only show MAC addresses. Is it possible to make them show Device Names/IP addresses instead? Or both?
________________________________

**Comment by PacoCT** [comment]
> @PacoCT I'm not entirely sure what's causing your errors. I think it's because you're trying to run two versions of the same integration in parallel (it looks like you renamed some things to `eero_standard`)? The errors regarding `error.network.premium.not.capable` have been addressed in the beta, and I can tell from the formatting of the exception logs that they're coming from the (older) non-beta version. Please re-try with the [latest](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b1) beta.

Great, @schmittx !

That was my fault. when I've installed the beta, I renamed the original eero folder to eero_standard instead of deleting it.
Now, I've removed eero and eero_standard folders, copied the new one from the latest beta 1.5.0b1, restarted homeassitant, and went to Configure the eero integration. 

My network was discovered, the four eero-routers were there, and all devices connected to the mesh network appeared in the configuration windows :-)))

Now I've to start playing to remove unwanted devices

Thank you very much!

**Comment by schmittx** [comment]
@RuneMason1 Glad to hear it's all good now. If you give the client/device a [nickname](https://support.eero.com/hc/en-us/articles/211096103-How-do-I-identify-the-devices-on-my-network-and-assign-nicknames) via the Eero app, then the integration will use that to help identify. IP addresses are too unstable for identification and hostnames aren't guaranteed to be unique within a network.

@PacoCT Good stuff. Let me know if run into any further problems.

**Comment by schmittx** [comment]
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0).
