### ISSUE TITLE
Wrong unit for sensor download_speed and upload_speed

### ISSUE THREAD

**Issue by marioarand** [schmittx/home-assistant-eero#78]
Hi! The integration is working perfectly for me, but I saw that the unit of the up- and download_speed entities are not correct. It shows me something arround 94 MB/s, but in the eero iOS-App it's actually 94 Mbit/s.

Not correct:
`sensor.SSID_download_speed`
`sensor.SSID_upload_speed`

Correct:
`sensor.SSID_DEVICE_wired_download_rate`
`sensor.SSID_DEVICE_wired_upload_rate`
`sensor.SSID_DEVICE_wireless_download_rate`
`sensor.SSID_DEVICE_wireless_upload_rate`

**Comment by schmittx** [comment]
Thanks for catching this, I'll include a fix in the next update.

**Comment by schmittx** [comment]
I published a beta [release](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0b0) with multiple bug fixes, give a try and let me know if it helps.

**Comment by schmittx** [comment]
Closing this as the beta updates have been reflected into newest release [here](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0).
