### ISSUE TITLE
No Data Usage Sensors.

### ISSUE THREAD

**Issue by TheRealFalseReality** [schmittx/home-assistant-eero#79]
I'm wondering if I'm doing something incorrect.
I really like this integration! Thank you for making it. I recently came from Google Wifi, but the network was so unreliable that I moved to Eero. 
I 've been looking for months to measure my network data usage, and got 1 step closer with this HACS integration with Data Usage (Weekly) showing up in the config setup. But I do not see any data_usage sensor anywhere.... I signed up for the Eero subscription (trial) to see if that was required, still nothing. Is there something else needed to be done to pull the usage into a sensor?
I have the api responses saved in the `\custom_components\eero\api\responses` and I see the data_usage.json populating! Just don't know how to bring that info into HA. 

`_2_2_networks_11542878_data_usage.json`:
```
    "end": "2024-02-04T04:59:00Z",
    "limit": "2023-09-30T00:00:00Z",
    "series": [
        {
            "sum": 15125909614,
            "type": "upload",
            "values": [
                {
                    "time": "2024-01-28T05:00:00Z",
                    "value": 12430372928
                },
                {
                    "time": "2024-01-29T05:00:00Z",
                    "value": 2695536686
                },
                {
                    "time": "2024-01-30T05:00:00Z",
                    "value": 0
                },
                {
                    "time": "2024-01-31T05:00:00Z",
                    "value": 0
                },
                {
                    "time": "2024-02-01T05:00:00Z",
                    "value": 0
                },
                {
                    "time": "2024-02-02T05:00:00Z",
                    "value": 0
                }
            ]
        },
```

Thank you!

**Comment by schmittx** [comment]
Can you check `_2_2_networks_11542878.json` and share the value that's being returned for `"premium_status"`?

**Comment by TheRealFalseReality** [comment]
> Can you check `_2_2_networks_11542878.json` and share the value that's being returned for `"premium_status"`?

Thanks for responding, its set to 'trialing'

**Comment by schmittx** [comment]
Thanks, are you sure there's no sensor entity? It has a `diagnostic` category so it won't show up in the front end by default. Go to the device config page or search all entities.

**Comment by schmittx** [comment]
I just pushed a new [update](https://github.com/schmittx/home-assistant-eero/releases/tag/1.5.0) that may fix any problems (if that's indeed happening here). Please update and confirm, then re-open if you're still experiencing the issue. Be sure to check the device page for `diagnostic` category sensors as mentioned above.

**Comment by Gotcha-1980** [comment]
I have installed the HACS integration today, selected the metrics for the Network, but am not seeing any data usage sensors at all:

![image](https://github.com/schmittx/home-assistant-eero/assets/59747960/477cc108-16c1-41c7-8c9f-5d351641d5c0)

I do not have premium ... is this required in order to see the usage sensors?

**Comment by schmittx** [comment]
Yes, Eero Plus subscription is required for data usage sensors.
