### ISSUE TITLE
Need individual device setup after initial install

### ISSUE THREAD

**Issue by rodhall** [schmittx/home-assistant-eero#8]
When I set up the Integration it gave me the chance to add individual devices. However, after installed the only option I have is to have the plugin automatically detect new profiles. The problem is this - most of us using Eero have device profiles per person that include laptops, etc which are not good for presence detection. We need the ability to determine if someone's phone is connected to figure out whether they are home or not. This method of presence detection is far better than the HA App, etc in my experience. With the old Eero custom integration I simply associated people's iPhone and Apple Watch to their Person profile and then I could tell when people were home with high precision.

I tried to create new profiles with just an iPhone in them but it doesn't really work in the Eero app.

**Comment by rodhall** [comment]
Hey Matt - I didn’t explain this clearly enough. I understand all of what you are saying. However, it comes down to what device tracker entities Eero makes available to use and when. 

The issue is that you can’t add single devices in the config after the initial installation. Also - at install I am finding only connected devices appear as options. If people don’t happen to be home/connected you can’t add their device as a tracker in Eero. 

Rod
***@***.***

**Comment by rodhall** [comment]
To expand on this, my daughter dropped her iPhone in water and ruined it. It was set up on Eero tracker as a device. I am now unable to set her new phone up as a device without uninstalling and re-installing the Eero integration completely as far as I can tell.

**Comment by Holbroser21** [comment]
If you have the latest version, then you should be able to configure which devices are tracked on the HA side. 

If you click 'OPTIONS' on the integration, then 'SUBMIT' on the network selection popup, you should be able to access more settings about wired/wireless devices, profiles and eero hubs. Do those options not appear for you?

Additionally I will let schmittx confrim, but the limitation on connected devices only is an eero limitation. I find that even if I name a device in the eero app, if it is not seen by the network for a couple of weeks then it drops out of the app. At that point I guess that it is not accessible by the API.

**Comment by schmittx** [comment]
@rodhall Thanks for clarifying your concerns, I believe I understand now.

@Holbroser21 is correct on both points.

Use the "Options" feature for the integration to update your config after it's been setup.

The Eero API only shows devices that have recently been connected. I believe the timeout is 1 week, meaning if a device hasn't been connected in a week, it's not shown in the app and isn't available via the API.

**Comment by rodhall** [comment]
Aha! That works fine. The UI just confused me. I would have expected to see devices in that first window. I would add text saying "Press Submit for more device and profile options" or something like that to make it clear. What I was thinking it that I could only select a Network in options and that was it.

**Comment by schmittx** [comment]
Glad you got it worked out. It sounds like you're all set, so I'll close the issue but if you have other problems or suggestions, feel free to re-open or start a new one.
