### ISSUE TITLE
Person tracking

### ISSUE THREAD

**Issue by mikefrantz** [schmittx/home-assistant-eero#80]
How can I see in Home assistant what devices are on the network so I might track them or see who is home? Thanks for all you are doing on this project. I applaud you.
Thanks again,
Mike

**Comment by schmittx** [comment]
When you setup the integration it'll prompt you to select network resources, wired and wireless clients are towards the bottom. A variety of entities are created for each configured client (ex. binary sensors, device tracker, etc.).

**Comment by mikefrantz** [comment]
Everything is working great and I appreciate all the hard work you put into this. Is there a way to notify me if a new device has connected to the eero network?
