### ISSUE TITLE
failed to setup error

### ISSUE THREAD

**Issue by askjano** [schmittx/home-assistant-eero#82]
after updating to ha 2024.6.0 for core and supervisor the eero integration no longer works. upon restarting after installing the ha updatei  get a failed to setup error. if i remove the integration and try to re-add it i get prompted for the account info and it lets me add it but fails to properly setup. 

<img width="707" alt="Screen Shot 2024-06-06 at 20 29 30" src="https://github.com/schmittx/home-assistant-eero/assets/124292790/d3a4497f-7567-42c2-9f85-cd55e9cf17ed">

when i press the configure button i get the following error:

 Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble 

<img width="555" alt="Screen Shot 2024-06-06 at 20 29 41" src="https://github.com/schmittx/home-assistant-eero/assets/124292790/475969eb-b61f-44e6-8bb7-ba24ff2371d0">

in the logs i see the following errors:

> 024-06-05 19:27:05.679 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry j for eero
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/__init__.py", line 149, in async_setup_entry
>     device_registry = hass.helpers.device_registry.async_get(hass)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: async_get() takes 1 positional argument but 2 were given
> 2024-06-05 19:27:11.466 ERROR (MainThread) [aiohttp.server] Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
>     resp = await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
>     result = await handler(request, **request.match_info)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
>     return await func(self, request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
>     return await super().post(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
>     return await method(view, request, data, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
>     return await self._post_impl(request, data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
>     result = await self._flow_mgr.async_init(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 343, in async_init
>     result = await self._async_handle_step(flow, flow.init_step, data)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
>     result: _FlowResultT = await getattr(flow, method)(user_input)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/eero/config_flow.py", line 224, in async_step_init
>     self.coordinator = self.hass.data[DOMAIN][self.config_entry.entry_id][DATA_COORDINATOR]
>                        ~~~~~~~~~~~~~~^^^^^^^^
> KeyError: 'eero'

**Comment by askjano** [comment]
not sure what changed but everything is now working again.

**Comment by mikefrantz** [comment]
It is not working today, just like last week. Whatever you did last week fixed it.

**Comment by askjano** [comment]
eero had an outage last week which caused a lot of issues for users. this included not being able to access settings or set up new devices or network. outage lasted almlost all day. it may be something similar today. the ha logs show the integration not being able to connect to eero api

**Comment by mikefrantz** [comment]
Thanks for looking into it and letting us know.

**Comment by schmittx** [comment]
Closing for now as this appears to be a result of an eero outage. Please re-open if problems persist.
