### ISSUE TITLE
Feature Request: Disable the 5Ghz network via Home Assistant

### ISSUE THREAD

**Issue by garyjohnwalker** [schmittx/home-assistant-eero#87]
One of the troubleshooting options in the Eero app is to disable the 5Ghz network for about 10 minutes.
This is useful if you have a device that is 2.4Ghz only and has lost the network. I often find that disabling 5Ghz allows it to connect again.
Given a lot of WiFi devices that are compatible with Home Assistant are 2.4Ghz, it would be useful to be able to call the same functionality from Home Assistant.

This could then either be scheduled as a daily task (nightly clean up/reconnect) or called on detection of a device that is known to be 2.4Ghz disconnecting.

**Comment by schmittx** [comment]
Added in [1.6.0](https://github.com/schmittx/home-assistant-eero/releases)

**Comment by garyjohnwalker** [comment]
Upgraded and tested. Works like a charm.

Thanks Matt
