### ISSUE TITLE
No networks shown in list

### ISSUE THREAD

**Issue by bryanhughes** [schmittx/home-assistant-eero#92]
I installed the integration and followed the instructions for creating second admin account. I do not see the list of networks. I decided to try the main account, and still do not see anything.

<img width="699" alt="image" src="https://github.com/user-attachments/assets/2817f932-3787-4ab1-8106-75f2467b7a49">

**Comment by strickersuk** [comment]
See the other issue, rolling back to 1.5.0 seems to work.

**Comment by michaelthompson1991** [comment]
Same problem, had it for a while but I can’t see how to roll back in hacs

**Comment by tferritto** [comment]
@michaelthompson1991 https://hacs.xyz/docs/faq/select_version/

**Comment by michaelthompson1991** [comment]
Thanks, I fixed it after I posted and it's now working 👍🏻

**Comment by strickersuk** [comment]
Is this integration still being supported? Not complaining just curious?

**Comment by schmittx** [comment]
This should be fixed in [1.6.1](https://github.com/schmittx/home-assistant-eero/releases/tag/1.6.1), please update and confirm if the issue is resolved.

**Comment by michaelthompson1991** [comment]
I can confirm 1.6.1 has resolved my issues, now upgraded from 1.5 to 1.6.1 and it is working
