### ISSUE TITLE
Feature Request: Sensor to show if updates pending

### ISSUE THREAD

**Issue by lloydbayley** [schmittx/home-assistant-eero#94]
G'day,

Would it be possible (is it available in the dataset) to have a sensor that shows when an update is available to install.
Something like: Update Available: Boolean : Yes/No
I don't even think the version number would be important but as I said, I don't know what the returned dataset contains, so that could be implemented as well if need be.

A few days prior to an update, the Eero app shows it but there is no real notification unless you check your Eero app manually.

Since there is no way to turn off the auto-update and only choice to choose which timeframe should be used for updates, I believe it would be handy to have a sensor which we could automate for a notification so it could be done when we are ready (within those few days) and not when it just happens.

Just a thought. What think ye?

**Comment by schmittx** [comment]
This integration already generates `update` entities ([info](https://developers.home-assistant.io/docs/core/entity/update)), which indicate if a firmware update is available. You can use create an automation using the `update` entity as a trigger.
